# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debtinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='debtor',
            table='tbl_due_listing',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='tb_profiles',
        ),
    ]
